employee/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.employee_create, name='create-employee'),
    path('create-cv/', views.create_cv, name='create-cv'),
    path('my-cv/', views.my_cv, name='my-cv'),
    path('get-cv/<int:n>', views.get_cv, name='get-cv'),
    path('my-cv/<int:pk>', views.MyCVDetailView.as_view(), name='my-cv-info'),
    path('cv/<pk>', views.CVDetailView.as_view(), name='cv-info'),
    path('cv-edit/<int:id>', views.edit_cv, name="cv-edit"),
    path('delete-cv/<int:id>', views.delete_cv, name='delete-cv'),
    path('refresh-cv/<int:id>', views.refresh_cv, name='refresh-cv'),
    path('chosen', views.chosen_cvs, name='hirer-chosen'),
    path('chosen/<int:id>', views.add_to_chosen, name='chosen-cv'),
    path('suitable-cv/<int:id>', views.suitable_cvs, name='suitable-cvs'),
    path('response/<int:id>', views.make_response, name='make-response'),
    path('my-responses', views.my_responses, name='my-responses')
]

hirer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/company', views.company_create, name='create-company'),
    path('register/enterpreneuer', views.enterpreneuer_create, name='create-enterpreneuer'),
    path('type', views.hirer_type, name='hirer-type'),
    path('all-companies/', views.company_catalog, name='company-catalog'),
    path('by-sphere/<str:sphere>', views.companies_by_sphere, name='companies-by-sphere'),
    # path('hirer-info/<int:id>/', views.hirer_info, name='hirer-info'),
]

ishim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main.views import (
    home, login_view, 
    activate_user, reg_type, 
    activate_message, profile,
    delete_user, password_edit,
    company_name_edit, phone_num_edit,
    sphere_edit, city_edit, 
    logo_edit, first_name_edit,
    last_name_edit
)

from main import tm_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('employee/', include('employee.urls')),
    path('hirer/', include('hirer.urls')),
    path('vacancy/', include('vacancy.urls')),
    path('articles/', include('articles.urls')),
    path('search/', include('search.urls')),
    path('contacts/', include('contacts.urls')),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
            template_name='main/logout.html'
        ),
        name='logout'),
    path('activate-user/<uidb64>/<token>', activate_user, name='activate'),
    path('register/', reg_type, name='register'),
    path('message/', activate_message, name='activate-message'),
    path('profile/', profile, name='profile'),
    path('delete-me/', delete_user, name='delete-me'),
    path('edit/password', password_edit, name='edit-password'),
    path('edit/company-name', company_name_edit, name='edit-company'),
    path('edit/phone', phone_num_edit, name='edit-phone'),
    path('edit/sphere', sphere_edit, name='edit-sphere'),
    path('edit/city', city_edit, name='edit-city'),
    path('edit/first_name', first_name_edit, name='edit-first-name'),
    path('edit/last_name', last_name_edit, name='edit-last-name'),
    path('edit/logo', logo_edit, name='logo-edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


tm_urlpatterns = [
    path('tm/', tm_views.home, name='home-tm'),
    path('tm/employee/', include('employee.tm_urls')),
    path('tm/hirer/', include('hirer.tm_urls')),
    path('tm/vacancy/', include('vacancy.tm_urls')),
    path('tm/articles/', include('articles.tm_urls')),
    path('tm/search/', include('search.tm_urls')),
    path('tm/contacts/', include('contacts.tm_urls')),
    path('tm/login/', tm_views.login_view, name='login-tm'),
    path('tm/logout/', auth_views.LogoutView.as_view(
            template_name='tm_main/logout.html'
        ),
        name='logout-tm'),
    path('tm/activate-user/<uidb64>/<token>', tm_views.activate_user, name='activate-tm'),
    path('tm/register/', tm_views.reg_type, name='register-tm'),
    path('tm/message/', tm_views.activate_message, name='activate-message-tm'),
    path('tm/profile/', tm_views.profile, name='profile-tm'),
    path('tm/delete-me/', tm_views.delete_user, name='delete-me-tm'),
    path('tm/edit/password', tm_views.password_edit, name='edit-password-tm'),
    path('tm/edit/company-name', tm_views.company_name_edit, name='edit-company-tm'),
    path('tm/edit/phone', tm_views.phone_num_edit, name='edit-phone-tm'),
    path('tm/edit/sphere', tm_views.sphere_edit, name='edit-sphere-tm'),
    path('tm/edit/city', tm_views.city_edit, name='edit-city-tm'),
    path('edit/first_name', tm_views.first_name_edit, name='edit-first-name-tm'),
    path('edit/last_name', tm_views.last_name_edit, name='edit-last-name-tm'),
    path('tm/edit/logo', tm_views.logo_edit, name='logo-edit-tm'),
]


urlpatterns.extend(tm_urlpatterns)

admin.site.site_header = 'ISHIM admin page'
admin.site.site_title = 'ISHIM'

vacancy/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.VacancyListView.as_view(), name='vacancies-all'),
    path('delete/<pk>', views.delete_my_vacancy, name='vacancy-delete'),
    path('edit/<int:id>', views.edit_vacancy, name='vacancy-edit'),
    path('create/', views.vacancy_create, name='create-vacancy'),
    path('refresh/<id>', views.refresh, name='refresh-vacancy'),
    path('my/', views.my_vacancies, name='my-vacancies'),
    path('my/<int:pk>', views.MyVacancyDetailView.as_view(), name='my-vacancy-info'),
    path('<int:pk>', views.VacancyDetailView.as_view(), name='vacancy-info'),
    path('chosen/', views.chosen_vacancies, name='employee-chosen'),
    path('chosen/<id>', views.add_to_chosen, name='chosen-vacancy'),
    path('get/<int:n>', views.get_vacancies, name='get-vacancies'),
    path('suitable/<int:id>', views.suitable_vacancies, name='suitable-vacancies'),
    path('response-notifications/', views.response_notifications, name='response-notifications'),
    path('<int:pk>/responses', views.vacancy_responses, name='vacancy-responses'),
]

employee/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from rest_framework import serializers
from vacancy.models import Vacancy


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    city = models.CharField(max_length=65)
    phone_num = PhoneNumberField()
    sex = models.CharField(max_length=65)
    birth_date = models.DateField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class CV(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=65)
    last_name = models.CharField(max_length=65)
    birth_date = models.DateField()
    mobile_num = models.CharField(max_length=25)
    email = models.EmailField()
    registration = models.CharField(max_length=100)
    sex = models.CharField(max_length=65)
    position = models.CharField(max_length=65)
    sphere = models.CharField(max_length=100)
    min_salary = models.IntegerField()
    busyness = models.CharField(max_length=65, default='')
    work_graph = models.CharField(max_length=65)
    about = models.TextField()
    views = models.IntegerField(default=0)
    suitable_vacancies = models.ManyToManyField(Vacancy, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name}\'s CV {self.pk}'


class CVSerializer(serializers.ModelSerializer):
    class Meta:
        model = CV
        fields = '__all__'


class CVAttr(models.Model):
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, null=True, blank=True)


class KnownLanguage(CVAttr):
    language = models.CharField(max_length=25)
    level = models.CharField(max_length=65)


class KnownProgram(CVAttr):
    program = models.CharField(max_length=65)


class WorkExperience(CVAttr):
    position = models.CharField(max_length=65)
    org_name = models.CharField(max_length=100)
    responsibilities = models.TextField()
    start_year = models.CharField(max_length=65)
    end_year = models.CharField(max_length=65)

    def __str__(self):
        return f'WorkExpr cv:{self.cv.id}'


class Education(CVAttr):
    degree = models.CharField(max_length=65)
    establishment = models.CharField(max_length=65)
    faculty = models.CharField(max_length=65)
    specialization = models.CharField(max_length=100)
    start_year = models.IntegerField()
    end_year = models.IntegerField()


class Response(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)


class ChosenVacancy(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)


class ChosenCv(models.Model):
    hirer = models.ForeignKey(User, on_delete=models.CASCADE)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)

employee/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *


class UserCreateForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'city', 'phone_num', 'sex']


class CVCreationForm(forms.ModelForm):
    class Meta:
        model = CV
        fields = [
            'first_name', 
            'last_name', 
            'mobile_num', 
            'email', 
            'registration', 
            'sex', 
            'position', 
            'sphere', 
            'min_salary',
            'busyness',
            'work_graph',
            'about'
            ]


class WorkExpCreateForm(forms.ModelForm):
    class Meta:
        model = WorkExperience
        fields =[
            'position',
            'org_name',
            'responsibilities',
            'start_year',
            'end_year'
        ]


class EduCreateForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = [
            'degree',
            'establishment',
            'faculty',
            'specialization',
            'start_year',
            'end_year',
        ]

employee/templates/employee/cv_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
   <svg display="none">
      <symbol id="favorites__str" viewBox="0 0 28 27">
         <g>
            <path
               d="M14 1L18.017 9.13603L27 10.4487L20.5 16.7782L22.034 25.72L14 21.496L5.966 25.72L7.5 16.7782L1 10.4487L9.983 9.13603L14 1Z"
               stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
         </g>
      </symbol>
   </svg>
   <div class="container__main pad-0 w-1920">
      {% include 'main/header_hirer.html' %}
      <div class="container__content">
         <div class="my__vac__view">
            <h1 class="mvv__headline">{{ object.position }}</h1>
            <h3 class="mvv__salary">{{ object.first_name }} {{ object.last_name }}</h3>
            <span class="mvv__main__info">{{ object.sex }}, {{ object.birth_date|date:"Y.m.d" }}</span>
            <span class="mvv__main__info">{{ object.registration }}</span>
            <span class="mvv__main__info">{{ object.email }}</span>

            <div class="mvv__refresh__in__search__btn__wrapper"  id="fav__btn__wrapper">
               <button class="mvv__refresh__in__search__btn green__btn">Получить контакты</button>
               <svg width="30px" height="30px">
                  <use xlink:href="#favorites__str" width="30px" height="30px" class="vac__ico{% for chosen in user.chosencv_set.all %}{% if chosen.cv == object %}__selected{% endif %}{% endfor %}" data-link="{% url 'chosen-cv' object.id %}"></use>
               </svg>
            </div>

            <h4 class="mvv__subtitle">{{ object.position }}
               <span>{{ object.min_salary }} м</span>
            </h4>
            <p class="mvv__info">
               <span>{{ object.sphere }}</span>

               <span>График работы: {{ object.work_graph }}</span>

               <span>Занятость: {{ object.busyness }}</span>
            </p>
            <h4 class="mvv__subtitle">Опыт работы</h4>
            {% for cvattr in object.cvattr_set.all %}
               {% if cvattr.workexperience %}
            <p class="mvv__info">
               <span>{{ cvattr.workexperience.positon }}</span>

               <span>{{ cvattr.workexperience.org_name }}</span>

               <span>{{ cvattr.workexperience.start_year }} - {{ cvattr.workexperience.end_year }}</span>

               <span>Обязанности: <br>
                  {{ cvattr.workexperience.responsibilities }}</span>
            </p>
            {% endif %}
               {% endfor %}
            <h4 class="mvv__subtitle">Образование</h4>
            {% for cvattr in object.cvattr_set.all %}
            {% if cvattr.education %}
            <p class="mvv__info">
               <span>{{ cvattr.education.degree }}</span>

               <span>{{ cvattr.education.establishment }}</span>

               <span>{{ cvattr.education.start_year }} - {{ cvattr.education.end_year }}</span>

               <span>Факультет: {{ cvattr.education.faculty }}</span>

               <span>Специальность: {{ cvattr.education.specialization }}</span>

            </p>
            {% endif %}
            {% endfor %}
            <h4 class="mvv__subtitle">Знание программ</h4>
            <p class="mvv__info">
               {% for cvattr in object.cvattr_set.all %}
                  {% if cvattr.knownprogram %}
                  <span>- {{ cvattr.knownprogram.program }}</span>
                  {% endif %}
                  {% endfor %}
            </p>
            <h4 class="mvv__subtitle">Владение языками</h4>
            <p class="mvv__info">
               {% for cvattr in object.cvattr_set.all %}
               {% if cvattr.knownlanguage %}
               <span>{{ cvattr.knownlanguage.language }} - {{ cvattr.knownlanguage.level }}</span>
               {% endif %}
               {% endfor %}
            </p>
            <h4 class="mvv__subtitle">О себе</h4>
            <p class="mvv__info">
               {{ object.about }}
            </p>
         </div>

         <a href="" class="mvv__link">У соискателя есть ещё резюме</a>
         {% for cv in object.employee.cv_set.all %}
         <a href="{% url 'cv-info' cv.id %}" class="mvv__another__resumes">
            <h4 class="mvv__subtitle">
               {{ cv.first_name }} {{ cv.last_name }}
            </h4>
            <p class="mvv__main__info">
               {{ cv.position }}
            </p>
         </a>
         {% endfor %}

      </div>
   </div>
   <script src="{% static 'scripts/header.js' %}"></script>
   <script src="{% static 'scripts/favourtie.js' %}"></script>
{% endblock %}

employee/templates/employee/my_cv.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
      <div class="container__main pad-0 w-1920">
         {% include 'main/header_employee.html' %}
         <div class="container__content">
            <div class="my__vac">
               <h1 class="my__vac__title">Мои Резюме</h1>
               {% for cv in cv_list %}
               <div class="my__vac__item">

                  <h2 class="my__vac__item__title"><a href="{% url 'my-cv-info' cv.id %}">{{ cv.position }}</a></h2>
                  <h3 class="my__vac__item__subtitle">{{ cv.min_salary }} ман.</h3>

                  <a href="" class="amount__resp">{{ cv.chosencv_set.count }} человек отметили это резюме</a>

                  <span>Резюме обновлено {{ cv.creation_date|date:"m.d"}}</span>

                  <a href="{% url 'refresh-cv' cv.id %}" class="refresh__in__search__btn green__btn">Обновить в поиске</a>

                  <a href="{% url 'cv-edit' cv.id %}" class="edit__btn purp__btn">Редактировать</a>

                  <a href="{% url 'suitable-vacancies' cv.id %}" class="suitable__link">{{ cv.suitable_vacancies.count }} подходящих вакансий</a>
               </div>
               {% endfor %}
               <a href="{% url 'create-cv' %}" class="add__vac"><span>+</span>Добавить новое резюме</a>
            </div>
         </div>    
      </div>
      <script src="{% static 'scripts/header.js' %}"></script>
      {% endblock %}

employee/templates/employee/my_cv_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
      <div class="container__main pad-0 w-1920">
         {% include 'main/header_employee.html' %}
         <div class="container__content">
            <div class="my__vac__view">
               <h1 class="mvv__headline">Моё резюме</h1>
               <h3 class="mvv__subtitle">{{ object.first_name }} {{ object.last_name }}</h3>
               <span class="mvv__main__info">{{ object.sex }}, {{ object.birth_date|date:"Y.m.d" }}</span>
               <span class="mvv__main__info">{{ object.registration }}</span>
               <span class="mvv__main__info">{{ object.mobile_num }}</span>
               <span class="mvv__main__info">{{ object.email }}</span>
               <span class="mvv__main__info">Опубликовано в {{ object.creation_date|date:"H:i" }}</span>
               <span class="mvv__main__info">{{ object.views }} просмотров</span>
               <a href="{% url 'refresh-cv' object.id %}" class="mvv__refresh__in__search__btn green__btn">Обновить в поиске</a>
               <a href="" class="mvv__edit__btn purp__btn">Редактировать</a>
               <h4 class="mvv__subtitle">{{ object.position }}
               </h4>
               <p class="mvv__info">
                  <span>{{ object.sphere }}</span>
                  
                  <span>График работы: {{ object.work_graph }}</span>
                
                  <span>Пол: {{ object.sex }}</span>
                  
                  <span>Занятость:  {{ object.busyness }}</span>
               </p>
               <h4 class="mvv__subtitle">Опыт работы</h4>
               {% for cvattr in object.cvattr_set.all %}
               {% if cvattr.workexperience %}
               <p class="mvv__info">
                  <span>{{ cvattr.workexperience.positon }}</span>
                  
                  <span>{{ cvattr.workexperience.org_name }}</span>
                  
                  <span>{{ cvattr.workexperience.start_year }} - {{ cvattr.workexperience.end_year }}</span>
               </p>
               <h4 class="mvv__subtitle">Обязанности:</h4>
               <p class="mvv__info">
                  {{ cvattr.workexperience.responsibilities }}
               </p>
               {% endif %}
               {% endfor %}
               <h4 class="mvv__subtitle">Образование
               </h4>
               {% for cvattr in object.cvattr_set.all %}
                  {% if cvattr.education %}
               <p class="mvv__info">
                  <span>
                     {{ cvattr.education.degree }}
                  </span>
                  
                  <span>{{ cvattr.education.establishment }}</span>
                  
                  <span>{{ cvattr.education.start_year }} - {{ cvattr.education.end_year }}</span>

                  <span>Факультет: {{ cvattr.education.faculty }}</span>

                  <span>Специальность: {{ cvattr.education.specialization }}</span>

               </p>
               {% endif %}
               {% endfor %}
               <h4 class="mvv__subtitle">Знание программ</h4>
               <p class="mvv__info">
                  {% for cvattr in object.cvattr_set.all %}
                  {% if cvattr.knownprogram %}
                  <span>- {{ cvattr.knownprogram.program }}</span>
                  {% endif %}
                  {% endfor %}
               </p>
               <h4 class="mvv__subtitle">Владение языками</h4>
               <p class="mvv__info">
                  {% for cvattr in object.cvattr_set.all %}
                  {% if cvattr.knownlanguage %}
                  <span>{{ cvattr.knownlanguage.language }} - {{ cvattr.knownlanguage.level }}</span>
                  {% endif %}
                  {% endfor %}
               </p>

               <h4 class="mvv__subtitle">О себе</h4>
               <p class="mvv__info">
                  {{ object.about }}
               </p>
              
               <a href="{% url 'delete-cv' cv.id %}" class="mvv__delete__btn">Удалить</a>
            </div>
         </div>    
      </div>
      <script src="{% static 'scripts/header.js' %}"></script>
      {% endblock %}

employee/templates/employee/my_responses.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<svg display="none">
   <symbol id="favorites__str" viewBox="0 0 28 27">
      <g>
         <path
            d="M14 1L18.017 9.13603L27 10.4487L20.5 16.7782L22.034 25.72L14 21.496L5.966 25.72L7.5 16.7782L1 10.4487L9.983 9.13603L14 1Z"
            stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </g>
   </symbol>
</svg>
<div class="container__main pad-0 w-1920">
   {% include 'main/header_employee.html' %}
   <div class="container__content">
      <div class="my__responses">
         <h1 class="my__responses__title">Мои отклики</h1>
         <h2 class="my__responses__subtitle">Вакансии на которые вы откликнулись</h2>
         {% for response in responses %}
         <div class="my__responses__item__wrapper">
            <div class="my__responses__item">
               <h3 class="my__responses__item__headline">{{ response.vacancy.position }}</h3>
               <h3 class="my__responses__item__headline">{{ response.vacancy.min_salary }} манат</h3>
            </div>

            <div class="my__responses__item">
               <div class="my__responses__item__additionally">{{ response.vacancy.creator.hirer.company_name }}</div>
               <a href="{% url 'make-response' response.vacancy.id %}" class="my__responses__item__btn">Отменить
                  отклик</a>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>
<script src="{% static 'scripts/header.js' %}"></script>
{% endblock %}

employee/templates/employee/suitable_cvs.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}

<svg display="none">
   <symbol id="favorites__str" viewBox="0 0 28 27">
      <g>
         <path
            d="M14 1L18.017 9.13603L27 10.4487L20.5 16.7782L22.034 25.72L14 21.496L5.966 25.72L7.5 16.7782L1 10.4487L9.983 9.13603L14 1Z"
            stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </g>
   </symbol>
</svg>

<div class="container__main pad-0 w-1920">
   {% include 'main/header_hirer.html' %}

   <div class="container__content">

      <div class="e__rec" id="fav__btn__wrapper">
         <h1 class="e__rec__title">Подходящие резюме</h1>
         <div class="e__rec__inner">
            {% for cv in cv_list %}
            <div class="vacancy__card" id="fav__btn__wrapper">
               <div class="vac__card__inner">
                  <div class="vac__heading">
                     <h2 class="vac__heading__item">{{ cv.position }}</h2>
                     <h2 class="vac__heading__item">{{ cv.min_salary }} манат</h2>
                  </div>
                  <div class="vac__heading">
                     <h2 class="vac__heading__item">{{ cv.creation_date|date:"Y.m.d" }}</h2>
                     <svg width="26px" height="24px">
                        <use xlink:href="#favorites__str" width="26px" height="24px"
                           class="vac__ico{% for chosen in user.chosencv_set.all %}{% if chosen.cv == cv %}__selected{% endif %}{% endfor %}"
                           data-link="{% url 'chosen-cv' cv.id %}"></use>
                     </svg>
                  </div>
                  <div class="vac__categories">
                     <span class="vac__cat__item two-col">{{ cv.sphere }}</span>
                     <span class="vac__cat__item">{{ cv.registration }}</span>
                     <span class="vac__cat__item">{{ cv.busyness }}</span>
                     <span class="vac__cat__item">{{ cv.birth_date|date:"Y.m.d" }}</span>
                     <span class="vac__cat__item">{{ cv.sex }}</span>
                     <span class="vac__cat__item two-col">{{ cv.work_graph }}</span>
                  </div>
                  <div class="vac__btns">
                     <a href="{% url 'cv-info' cv.id %}" class="vac__btns__item purp__btn" target="_blank">Подробнее</a>
                     <a href="" class="vac__btns__item green__btn" target="_blank">Получить контакты</a>
                  </div>
               </div>
            </div>
            {% endfor %}

         </div>
      </div>
   </div>
</div>
<script src="{% static 'scripts/header.js' %}"></script>
<script src="{% static 'scripts/favourtie.js' %}"></script>
{% endblock %}