hirer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/company', views.company_create, name='create-company'),
    path('register/enterpreneuer', views.enterpreneuer_create, name='create-enterpreneuer'),
    path('type', views.hirer_type, name='hirer-type'),
    path('all-companies/', views.company_catalog, name='company-catalog'),
    path('by-sphere/<str:sphere>', views.companies_by_sphere, name='companies-by-sphere'),
    # path('hirer-info/<int:id>/', views.hirer_info, name='hirer-info'),
]

ishim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main.views import (
    home, login_view, 
    activate_user, reg_type, 
    activate_message, profile,
    delete_user, password_edit,
    company_name_edit, phone_num_edit,
    sphere_edit, city_edit, 
    logo_edit, first_name_edit,
    last_name_edit
)

from main import tm_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('employee/', include('employee.urls')),
    path('hirer/', include('hirer.urls')),
    path('vacancy/', include('vacancy.urls')),
    path('articles/', include('articles.urls')),
    path('search/', include('search.urls')),
    path('contacts/', include('contacts.urls')),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
            template_name='main/logout.html'
        ),
        name='logout'),
    path('activate-user/<uidb64>/<token>', activate_user, name='activate'),
    path('register/', reg_type, name='register'),
    path('message/', activate_message, name='activate-message'),
    path('profile/', profile, name='profile'),
    path('delete-me/', delete_user, name='delete-me'),
    path('edit/password', password_edit, name='edit-password'),
    path('edit/company-name', company_name_edit, name='edit-company'),
    path('edit/phone', phone_num_edit, name='edit-phone'),
    path('edit/sphere', sphere_edit, name='edit-sphere'),
    path('edit/city', city_edit, name='edit-city'),
    path('edit/first_name', first_name_edit, name='edit-first-name'),
    path('edit/last_name', last_name_edit, name='edit-last-name'),
    path('edit/logo', logo_edit, name='logo-edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


tm_urlpatterns = [
    path('tm/', tm_views.home, name='home-tm'),
    path('tm/employee/', include('employee.tm_urls')),
    path('tm/hirer/', include('hirer.tm_urls')),
    path('tm/vacancy/', include('vacancy.tm_urls')),
    path('tm/articles/', include('articles.tm_urls')),
    path('tm/search/', include('search.tm_urls')),
    path('tm/contacts/', include('contacts.tm_urls')),
    path('tm/login/', tm_views.login_view, name='login-tm'),
    path('tm/logout/', auth_views.LogoutView.as_view(
            template_name='tm_main/logout.html'
        ),
        name='logout-tm'),
    path('tm/activate-user/<uidb64>/<token>', tm_views.activate_user, name='activate-tm'),
    path('tm/register/', tm_views.reg_type, name='register-tm'),
    path('tm/message/', tm_views.activate_message, name='activate-message-tm'),
    path('tm/profile/', tm_views.profile, name='profile-tm'),
    path('tm/delete-me/', tm_views.delete_user, name='delete-me-tm'),
    path('tm/edit/password', tm_views.password_edit, name='edit-password-tm'),
    path('tm/edit/company-name', tm_views.company_name_edit, name='edit-company-tm'),
    path('tm/edit/phone', tm_views.phone_num_edit, name='edit-phone-tm'),
    path('tm/edit/sphere', tm_views.sphere_edit, name='edit-sphere-tm'),
    path('tm/edit/city', tm_views.city_edit, name='edit-city-tm'),
    path('edit/first_name', tm_views.first_name_edit, name='edit-first-name-tm'),
    path('edit/last_name', tm_views.last_name_edit, name='edit-last-name-tm'),
    path('tm/edit/logo', tm_views.logo_edit, name='logo-edit-tm'),
]


urlpatterns.extend(tm_urlpatterns)

admin.site.site_header = 'ISHIM admin page'
admin.site.site_title = 'ISHIM'

vacancy/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.VacancyListView.as_view(), name='vacancies-all'),
    path('delete/<pk>', views.delete_my_vacancy, name='vacancy-delete'),
    path('edit/<int:id>', views.edit_vacancy, name='vacancy-edit'),
    path('create/', views.vacancy_create, name='create-vacancy'),
    path('refresh/<id>', views.refresh, name='refresh-vacancy'),
    path('my/', views.my_vacancies, name='my-vacancies'),
    path('my/<int:pk>', views.MyVacancyDetailView.as_view(), name='my-vacancy-info'),
    path('<int:pk>', views.VacancyDetailView.as_view(), name='vacancy-info'),
    path('chosen/', views.chosen_vacancies, name='employee-chosen'),
    path('chosen/<id>', views.add_to_chosen, name='chosen-vacancy'),
    path('get/<int:n>', views.get_vacancies, name='get-vacancies'),
    path('suitable/<int:id>', views.suitable_vacancies, name='suitable-vacancies'),
    path('response-notifications/', views.response_notifications, name='response-notifications'),
    path('<int:pk>/responses', views.vacancy_responses, name='vacancy-responses'),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    image = models.ImageField(default='article_default.jpg', upload_to='article_images')
    title = models.CharField(max_length=130)
    content = models.TextField()
    views = models.IntegerField(default=0)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ChosenArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.article.title}'

employee/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from rest_framework import serializers
from vacancy.models import Vacancy


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    city = models.CharField(max_length=65)
    phone_num = PhoneNumberField()
    sex = models.CharField(max_length=65)
    birth_date = models.DateField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class CV(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=65)
    last_name = models.CharField(max_length=65)
    birth_date = models.DateField()
    mobile_num = models.CharField(max_length=25)
    email = models.EmailField()
    registration = models.CharField(max_length=100)
    sex = models.CharField(max_length=65)
    position = models.CharField(max_length=65)
    sphere = models.CharField(max_length=100)
    min_salary = models.IntegerField()
    busyness = models.CharField(max_length=65, default='')
    work_graph = models.CharField(max_length=65)
    about = models.TextField()
    views = models.IntegerField(default=0)
    suitable_vacancies = models.ManyToManyField(Vacancy, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name}\'s CV {self.pk}'


class CVSerializer(serializers.ModelSerializer):
    class Meta:
        model = CV
        fields = '__all__'


class CVAttr(models.Model):
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, null=True, blank=True)


class KnownLanguage(CVAttr):
    language = models.CharField(max_length=25)
    level = models.CharField(max_length=65)


class KnownProgram(CVAttr):
    program = models.CharField(max_length=65)


class WorkExperience(CVAttr):
    position = models.CharField(max_length=65)
    org_name = models.CharField(max_length=100)
    responsibilities = models.TextField()
    start_year = models.CharField(max_length=65)
    end_year = models.CharField(max_length=65)

    def __str__(self):
        return f'WorkExpr cv:{self.cv.id}'


class Education(CVAttr):
    degree = models.CharField(max_length=65)
    establishment = models.CharField(max_length=65)
    faculty = models.CharField(max_length=65)
    specialization = models.CharField(max_length=100)
    start_year = models.IntegerField()
    end_year = models.IntegerField()


class Response(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)


class ChosenVacancy(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)


class ChosenCv(models.Model):
    hirer = models.ForeignKey(User, on_delete=models.CASCADE)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE)

vacancy/models.py
from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers


class Vacancy(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=65)
    sphere = models.CharField(max_length=100)
    min_salary = models.IntegerField(default=0)
    max_salary = models.IntegerField()
    registration = models.CharField(max_length=100, default='не имеет значения')
    experience = models.CharField(max_length=65)
    min_age = models.IntegerField()
    max_age = models.IntegerField()
    sex = models.CharField(max_length=65, default='не имеет значения')
    education = models.CharField(max_length=65)
    responsibilities = models.TextField()
    work_terms = models.TextField()
    busyness = models.CharField(max_length=65, default='')
    work_graph = models.CharField(max_length=65)
    payment = models.TextField(default='')
    views = models.IntegerField(default=0)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.creator.email} {self.position}'
    
    class Meta:
        verbose_name_plural = "Vacancies"


class NeededLanguage(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    language = models.CharField(max_length=25)
    level = models.CharField(max_length=65)


class VacancySerializer(serializers.ModelSerializer):
    class Meta:
        model = Vacancy
        fields = '__all__'

vacancy/forms.py
from django import forms
from .models import Vacancy


class VacancyCreateForm(forms.ModelForm):
    
    class Meta:
        model = Vacancy
        fields = [
            'position', 
            'sphere',
            'min_salary',
            'max_salary',
            'registration',
            'experience',
            'min_age',
            'max_age',
            'sex',
            'education',
            'responsibilities',
            'work_terms',
            'busyness',
            'work_graph',
            'payment',
        ]

vacancy/templates/vacancy/chosen.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<svg display="none">
   <symbol id="favorites__str" viewBox="0 0 28 27">
      <g>
         <path
            d="M14 1L18.017 9.13603L27 10.4487L20.5 16.7782L22.034 25.72L14 21.496L5.966 25.72L7.5 16.7782L1 10.4487L9.983 9.13603L14 1Z"
            stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </g>
   </symbol>
</svg>

<svg display="none">
   <symbol id="bookmark" viewBox="0 0 19 24">
      <g>
         <path
            d="M18 22.85L9.5 16.7806L1 22.85V3.42778C1 2.78389 1.25587 2.16638 1.71131 1.71108C2.16676 1.25578 2.78447 1 3.42857 1H15.5714C16.2155 1 16.8332 1.25578 17.2887 1.71108C17.7441 2.16638 18 2.78389 18 3.42778V22.85Z"
            stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </g>
   </symbol>
</svg>
<div class="container__main pad-0 w-1920">
   {% include 'main/header_employee.html' %}
   <div class="container__content">
      <div class="h__fav">
         <div class="h__fav__top">
            <h1 class="h__fav__top__title">Избранное</h1>

            <span class="h__fav__top__cat gren__color" id="vac_fav">Вакансии</span>
            <span class="h__fav__top__cat" id="articles_fav">Статьи</span>
         </div>

         <div class="h__fav__top__row"></div>
         <div class="vac__card__wrapper" id="fav__btn__wrapper">
            {% for vacancy in vacancies %}
            <div class="vacancy__card" id="fav__btn__wrapper">
               <div class="vac__card__inner">
                  <div class="vac__heading">
                     <h2 class="vac__heading__item">{{ vacancy.position }}</h2>
                     <h2 class="vac__heading__item">{{ vacancy.min_salary }} манат</h2>
                  </div>
                  <div class="vac__heading">
                     <h2 class="vac__heading__item">{{ vacancy.creation_date|date:"Y.m.d" }}</h2>
                     <svg width="26px" height="24px">
                        <use xlink:href="#favorites__str" width="26px" height="24px"
                           class="vac__ico{% for chosen in user.employee.chosenvacancy_set.all %}{% if chosen.vacancy == vacancy %}__selected{% endif %}{% endfor %}"
                           data-link="{% url 'chosen-vacancy' vacancy.id %}"></use>
                     </svg>
                  </div>
                  <div class="vac__categories">
                     <span class="vac__cat__item two-col">{{ vacancy.sphere }}</span>
                     <span class="vac__cat__item">{{ vacancy.registration }}</span>
                     <span class="vac__cat__item">{{ vacancy.experience }}</span>
                     <span class="vac__cat__item">{{ vacancy.min_age }} лет</span>
                     <span class="vac__cat__item">{{ vacancy.sex }}</span>
                     <span class="vac__cat__item two-col">{{ vacancy.education }}</span>
                  </div>
                  <div class="vac__btns">
                     <a href="{% url 'vacancy-info' vacancy.id %}" class="vac__btns__item purp__btn"
                        target="_blank">Подробнее</a>
                     <a href="{% url 'get-contact' id=vacancy.contact.id %}" class="vac__btns__item green__btn"
                        target="_blank">Получить контакты</a>
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>


         <div class="disappear" id="fav__wrapper2">
            {% for article in articles %}
            <div class="fav__article">
               <div class="fav__article__section">
                  <img src="{{ article.image.url }}" alt="Sorry got some error" class="fav__article__pic" width="100"
                     height="100">
               </div>

               <div class="fav__article__section" id="article__btn__wrapper">
                  <div class="fav__article__section__top">
                     <a href="{% url 'article-detail' article.id %}" class="article__subtitle">{{ article.title }}</a>
                     <svg width="19" height="24">
                        <use xlink:href="#bookmark" width="19" height="24"
                           class="vac__ico{% for chosen in article.chosenarticle_set.all %}{% if chosen.user == user %}__selected__purp{% endif %}{% endfor %}"
                           id="bookmarkbtn" data-link="{% url 'choose-article' article.id %}"></use>
                     </svg>
                  </div>
                  <div class="fav__article__section__bottom">
                     <div>{{ article.views}}</div>
                     <div>{{ article.creation_date|date:"Y.m.d" }}</div>
                  </div>
               </div>
            </div>


            {% endfor %}
         </div>



      </div>
   </div>
</div>
<script src="{% static 'scripts/header.js' %}"></script>
<script src="{% static 'scripts/favourtie.js' %}"></script>
<script src="{% static 'scripts/empl_fav.js' %}"></script>
<script src="{% static 'scripts/fav_art.js' %}"></script>

{% endblock %}

vacancy/templates/vacancy/my_vac.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
      <div class="container__main pad-0 w-1920">
         {% include 'main/header_hirer.html' %}
         <div class="container__content">
            <div class="my__vac">
               <h1 class="my__vac__title">Мои вакансии</h1>
               {% for vacancy in vacancies %}
                  <div class="my__vac__item">

                     <h2 class="my__vac__item__title"><a href="{% url 'my-vacancy-info' vacancy.id %}">{{ vacancy.position }}</a></h2>
                     <h3 class="my__vac__item__subtitle">{{ vacancy.min_salary }} ман.</h3>

                     <a href="{% url 'vacancy-responses' vacancy.id %}" class="amount__resp">{{ vacancy.response_set.count }} человек откликнулись к этой вакансии</a>

                     <span>Вакансия обновлена {{ vacancy.creation_date|date:'Y.m.d H:i' }}</span>

                     <a class="refresh__in__search__btn green__btn" href="{% url 'refresh-vacancy' vacancy.id %}">Обновить в поиске</a>

                     <a href="{% url 'vacancy-edit' vacancy.id %}" class="edit__btn purp__btn">Редактировать</a>

                     <a href="{% url 'suitable-cvs' vacancy.id %}" class="suitable__link">{{ vacancy.cv_set.count }} подходящих сотрудников</a>
                  </div>
               {% endfor %}

               <a href="{% url 'create-vacancy' %}" class="add__vac"><span>+</span>Добавить новую вакансию</a>
            </div>
            
         </div>    
      </div>
      <script src="{% static 'scripts/header.js' %}"></script>
      {% endblock %}

vacancy/templates/vacancy/my_vacancy_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
      <svg display="none" fill="none">
         <symbol id="mob__pic" viewBox="0 0 20 20">
            <path d="M18.3332 14.1V16.6C18.3341 16.8321 18.2866 17.0618 18.1936 17.2745C18.1006 17.4871 17.9643 17.678 17.7933 17.8349C17.6222 17.9918 17.4203 18.1113 17.2005 18.1856C16.9806 18.26 16.7477 18.2876 16.5165 18.2667C13.9522 17.9881 11.489 17.1118 9.32486 15.7084C7.31139 14.4289 5.60431 12.7219 4.32486 10.7084C2.91651 8.53438 2.04007 6.0592 1.76653 3.48337C1.7457 3.25293 1.77309 3.02067 1.84695 2.80139C1.9208 2.58211 2.03951 2.38061 2.1955 2.20972C2.3515 2.03883 2.54137 1.9023 2.75302 1.80881C2.96468 1.71532 3.19348 1.66692 3.42486 1.66671H5.92486C6.32928 1.66273 6.72136 1.80594 7.028 2.06965C7.33464 2.33336 7.53493 2.69958 7.59153 3.10004C7.69705 3.9001 7.89274 4.68565 8.17486 5.44171C8.28698 5.73998 8.31125 6.06414 8.24478 6.37577C8.17832 6.68741 8.02392 6.97347 7.79986 7.20004L6.74153 8.25837C7.92783 10.3447 9.65524 12.0721 11.7415 13.2584L12.7999 12.2C13.0264 11.976 13.3125 11.8216 13.6241 11.7551C13.9358 11.6887 14.2599 11.7129 14.5582 11.825C15.3143 12.1072 16.0998 12.3029 16.8999 12.4084C17.3047 12.4655 17.6744 12.6694 17.9386 12.9813C18.2029 13.2932 18.3433 13.6914 18.3332 14.1Z"  stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
         </symbol>
      </svg>
      <div class="container__main pad-0 w-1920">
         {% include 'main/header_hirer.html' %}
         <div class="container__content">
            <div class="my__vac__view">
               <h1 class="mvv__headline">Мои вакансии</h1>
               <h2 class="mvv__title">{{ object.position }}</h2>
               <h3 class="mvv__salary">{{ object.min_salary }} манат</h3>
               <span class="mvv__main__info">{{ object.creator.hirer.company_name }}</span>
               <span class="mvv__main__info">{{ object.sphere }}</span>
               <span class="mvv__main__info">{{ object.city }}</span>
               <span class="mvv__main__info">Опубликовано {{ object.creation_date|date:"Y.m.d H:i"}}</span>
               <div class="mvv__amount__resp">{{ vacancy.response_set.count }} откликов</div>
               <a href="{% url 'refresh-vacancy' object.id %}" class="mvv__refresh__in__search__btn green__btn">
                  Обновить в поиске
               </a>
               <a href="" class="mvv__see__all__resp purp__btn">Просмотреть все отклики</a>
               
               <h4 class="mvv__subtitle">Требования
               </h4>
               <p class="mvv__info">
                  <span>Опыт: {{ object.experience }}</span>
                  
                  <span>Возраст: от {{ object.min_age }} лет</span>
                
                  <span>Пол: {{ object.sex }}</span>
                  
                  <span>Образование: {{ object.education }}</span>
               </p>
               <h4 class="mvv__subtitle">Владение языками</h4>
               <p class="mvv__info">
                  {% for language in object.neededlanguage_set.all %}
                  <span>{{ language.language}} - {{ language.level }}</span>
                  {% endfor %}
               </p>
               <h4 class="mvv__subtitle">Обязанности:</h4>
               <p class="mvv__info">
                  {{ object.responsibilities }}
               </p>
               <h4 class="mvv__subtitle">Условия работы</h4>
               <p class="mvv__info">
                  <span>
                     {{ object.work_terms }}
                  </span>
                  
                  <span>Занятость: {{ object.busyness }}</span>
                  
                  <span>График: {{ object.work_graph }}</span>
               </p>
               <h4 class="mvv__subtitle">Дополнительная информация о зарплате</h4>
               <p class="mvv__info">
                  {{ object.payment }}
               </p>
               <div class="mvv__contacts bottom_mb">
                  <h4 class="mvv__subtitle">Контакты</h4>
                  {% with content=object.contact.content_as_list %}
                  <span>{{ content.0 }}</span>
                  <span>
                     <svg width="20" height="20" class="mr5">
                        <use xlink:href="#mob__pic" class="mob__pic" fill="none" stroke="black"></use>
                     </svg>
                     {{ content.1 }}</span>
                  <span><span class="mr5">✉</span>{{ content.2 }}</span>
                  {% endwith %}
               </div>
               <a href="{% url 'vacancy-edit' object.id %}" class="mvv__edit__btn purp__btn">Редактировать</a>
               <a href="{% url 'vacancy-delete' object.id %}" class="mvv__delete__btn">Удалить</a>
               <a href="{% url 'suitable-cvs' object.id %}" class="suitable__link">Найдено {{ vacancy.cv_set.count }} подходящий сотрудников</a>
            </div>
         </div>    
      </div>
      <script src="{% static 'scripts/header.js' %}"></script>
      {% endblock %}

vacancy/templates/vacancy/vacancy_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<svg display="none">
   <symbol id="favorites__str" viewBox="0 0 28 27">
      <g>
         <path
            d="M14 1L18.017 9.13603L27 10.4487L20.5 16.7782L22.034 25.72L14 21.496L5.966 25.72L7.5 16.7782L1 10.4487L9.983 9.13603L14 1Z"
            stroke="#C4C4C4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </g>
   </symbol>
</svg>
<div class="container__main pad-0 w-1920">
   {% include 'main/header_employee.html' %}
   <div class="container__content">
      <div class="my__vac__view" id="fav__btn__wrapper">
         <h1 class="mvv__headline">{{ object.position }}</h1>
         <h3 class="mvv__salary">{{ object.min_salary }} манат</h3>
         <span class="mvv__main__info">{{ object.creator.hirer.company_name }}</span>
         <span class="mvv__main__info">{{ object.sphere }}</span>
         <span class="mvv__main__info">{{ object.city }}</span>
         <span class="mvv__main__info">Опубликовано {{ object.creation_date|date:"Y.m.d H:i"}}</span>

         <div class="mvv__refresh__in__search__btn__wrapper">
            <a href="{% url 'make-response' object.id %}"
               class="mvv__refresh__in__search__btn green__btn">Откликнуться</a>
            <svg width="30px" height="30px">
               <use xlink:href="#favorites__str" width="30px" height="30px"
                  class="vac__ico{% for chosen in user.employee.chosenvacancy_set.all %}{% if chosen.vacancy == object %}__selected{% endif %}{% endfor %}"
                  data-link="{% url 'chosen-vacancy' object.id %}" data-link=""></use>
            </svg>
         </div>

         <h4 class="mvv__subtitle">Требования
         </h4>
         <p class="mvv__info">
            <span>Опыт: {{ object.experience }}</span>

            <span>Возраст: от {{ object.min_age }} лет</span>

            <span>Пол: {{ object.sex }}</span>

            <span>Образование: {{ object.education }}</span>
         </p>
         <h4 class="mvv__subtitle">Владение языками</h4>
         <p class="mvv__info">
            {% for language in object.neededlanguage_set.all %}
            <span>{{ language.language}} - {{ language.level }}</span>
            {% endfor %}
         </p>
         <h4 class="mvv__subtitle">Обязанности:</h4>
         <p class="mvv__info">
            {{ object.responsibilities }}
         </p>
         <h4 class="mvv__subtitle">Условия работы</h4>
         <p class="mvv__info">
            <span>
               {{ object.work_terms }}
            </span>

            <span>Занятость: {{ object.busyness }}</span>

            <span>График: {{ object.work_graph }}</span>
         </p>
         <h4 class="mvv__subtitle">Дополнительная информация о зарплате</h4>
         <p class="mvv__info">
            {{ object.payment }}
         </p>

         <div class="mvv__contacts bottom_mb">
            <h4 class="mvv__subtitle">Контакты</h4>
            {% with content=object.contact.content_as_list %}
            <span>{{ content.0 }}</span>
            <span>{{ content.1 }}</span>
            <span>{{ content.2 }}</span>
            {% endwith %}
         </div>
      </div>
   </div>
</div>
<script src="{% static 'scripts/header.js' %}"></script>
<script src="{% static 'scripts/favourtie.js' %}"></script>
{% endblock %}